import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Script from "next/script";
import { GoogleTagManager } from "@next/third-parties/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const GTM_ID = "GTM-5GXBGFPT";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          id="gtag-default"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag() {
                dataLayer.push(arguments);
              }

              gtag('consent', 'default', {
                ad_storage: 'denied',
                ad_user_data: 'denied',
                ad_personalization: 'denied',
                analytics_storage: 'denied',
                personalization_storage: 'denied',
                functionality_storage: 'denied',
                security_storage: 'denied',
              });
            `,
          }}
        />
        <Script
          src="/main.js?gcm=true&prefCenterOnly=false"
          // src="https://sahil-cctest.s3.ap-south-1.amazonaws.com/cookie_consent_17/408ecbd2-0ae8-4be8-9dc7-1da9c11abb89/main_5d20284.js?gcm=true&prefCenterOnly=false"
          id="lb-cookie-consent"
          strategy="beforeInteractive"
        />
        <GoogleTagManager gtmId={GTM_ID} />
        <Script
          src="./injectCookies.js"
          type="text/javascript"
          strategy="beforeInteractive"
        />
        <Script src="https://test-cookies.tiiny.site/show_alert.js" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
