export const componentsEnum = {
  platform: "Platform",
  platformPrivacy: "Platform-Privacy",
  platformSecurity: "Platform-Security",
  platformGovernance: "Platform-Governance",
  solution: "Solution",
  solutionPrivacy: "Solution-Privacy",
  solutionSecurity: "Solution-Security",
  solutionGovernance: "Solution-Governance",
  solutionIntegration: "Solution-Integration",
  resource: "Resource",
  blogs: "Blogs",
  newsRoom: "NewsRoom",
  customer: "Customer",
  contact: "Contact",
  company: "Company",
  companyAbout: "Company-About",
  companyCareers: "Company-Careers",
  companyPaternship: "Company-Partnership",
  whitePapers: "White-Papers",
  eBooks: "E-Books",
};

export const pathComponentMapper = {
  "/platform": componentsEnum.platform,
  "/platform/privacy-center": componentsEnum.platformPrivacy,
  "/platform/security": componentsEnum.platformSecurity,
  "/platform/governance-center": componentsEnum.platformGovernance,
  "/solution": componentsEnum.solution,
  "/solution/security": componentsEnum.solutionSecurity,
  "/solution/privacy": componentsEnum.solutionPrivacy,
  "/solution/governance": componentsEnum.solutionGovernance,
  "/solution/integrations": componentsEnum.solutionIntegration,
  "/company": componentsEnum.company,
  "/company/about": componentsEnum.companyAbout,
  "/company/partnership": componentsEnum.companyPaternship,
  "/company/career": componentsEnum.companyCareers,
  "/customer": componentsEnum.customer,
  "/resources": componentsEnum.resource,
  "/resources/newsroom": componentsEnum.newsRoom,
  "/resources/blogs": componentsEnum.blogs,
  "/resources/white-papers": componentsEnum.whitePapers,
  "/resources/e-books": componentsEnum.whitePapers,
};
